export type PaymentStatus = "paid" | "unpaid";
export type PaymentMethod = "cash" | "gcash";

export interface CheckoutData {
  customer: {
    id: number;
    name: string;
    phone: string;
  };
  services: Array<{
    id: number;
    name: string;
    price: number;
    quantity: number;
    icon?: string; // Optional if you want to show icons in summary
  }>;
  totalAmount: number;
}

export interface OrderRecord {
  id?: number; // Generated by database
  customer: {
    id: number;
    name: string;
    phone: string;
  };
  services: Array<{
    id: number;
    name: string;
    price: number;
    quantity: number;
  }>;
  totalAmount: number;
  paymentStatus: PaymentStatus;
  paymentMethod: PaymentMethod | null; // null if unpaid
  amountPaid: number;
  change: number;
  createdAt: string; // ISO date string
  updatedAt?: string; // For when status changes (unpaid -> paid)
}

export interface CheckoutValidation {
  valid: boolean;
  message?: string;
}
